# Sets default memory usage for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.20.1,1.21)
# The Forge version must agree with the Minecraft version
forge_version=47.4.10
# The Forge version range can use any version of Forge/FML as bounds or match the loader version range
forge_version_range=[47,)
# The loader version range can only use the major version of Forge/FML as bounds
loader_version_range=[47,)
# Mapping channel/version
mapping_channel=official
mapping_version=1.20.1

## Mod Properties

# The unique mod identifier
mod_id=magic_team
# The human-readable display name
mod_name=Magic Team
# License
mod_license=All Rights Reserved
# The mod version. See https://semver.org/
mod_version=2.3.3
# Babel Core generation consumed by Magic Team.
babel_core_version=2.0.0-SNAPSHOT
# Group ID
mod_group_id=com.gabri.magicteam
# Authors
mod_authors=Sato
# Description
mod_description=Server-side addon for Iron's Spells that enforces Vanilla team rules for spell targeting.
